# Section A — Exception Handling


In [ ]:
"""
1. Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError and
TypeError separately, printing an appropriate message for each. Use a finally block to print
'Operation attempted.' regardless of the outcome. Test it with valid numbers, division by zero, and a
string input.
"""

In [1]:
def safe_divide(a, b):
    try:
        result = a / b
        print(f"Result: {result}")
    except ZeroDivisionError:
        print("Error: Division by zero is not allowed.")
    except TypeError:
        print("Error: Both inputs must be numbers.")
    finally:
        print("Operation attempted.")

# Test cases
safe_divide(10, 2)  # valid division
safe_divide(10, 0)  # division by zero
safe_divide(10, "a")  # invalid type

Result: 5.0
Operation attempted.
Error: Division by zero is not allowed.
Operation attempted.
Error: Both inputs must be numbers.
Operation attempted.


In [4]:
"""
2. Write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you
define, inheriting from Exception) if age is negative or greater than 120. Catch this exception in a
calling block and print a user-friendly message. Test it with at least 3 different values.
""";

In [2]:
class InvalidAgeError(Exception):
    pass

def validate_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError(f"Invalid age: {age}")
    print(f"Age {age} is valid.")

for test_age in [25, -5, 130]:
    try:
        validate_age(test_age)
    except InvalidAgeError as e:
        print(f"Caught an error: {e}")

Age 25 is valid.
Caught an error: Invalid age: -5
Caught an error: Invalid age: 130


In [6]:
"""
3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list,
e.g. user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. Handle the following in
a single try block using multiple except clauses:
a) ValueError if the input is not a number.
b) ZeroDivisionError if the input is zero.
c) A generic Exception as a catch-all for anything else.
Print the result if successful, otherwise print which error occurred
""";

In [8]:
user_inputs = ['10', 'abc', '0', '5']

for inp in user_inputs:
    try:
        num = int(inp)
        result = 100 / num
        print(f"100/{num}:{result}")
    except ValueError:
        print(f"Error :'{inp}' is not a valid number.")
    except ZeroDivisionError:
        print("Error: cannot divide by zero.")
    except Exception as e:
        print(f"Unexpected error: {e}")

100/10:10.0
Error :'abc' is not a valid number.
Error: cannot divide by zero.
100/5:20.0


# Section B — NumPy

In [10]:
"""
4. Create a 1D NumPy array of integers from 1 to 20. Perform the following:
a) Reshape it into a 4x5 2D array.
b) Print the sum of each row and each column.
c) Extract all elements greater than 10 using boolean indexing.
d) Replace all even numbers in the array with -1.
""";

In [20]:
import numpy as np
arr = np.arange(1, 21)

arr_2d = arr.reshape(4 ,5)
print("4*5 Array:\n",arr_2d)

row_sum = arr_2d.sum(axis=1)
col_sum = arr_2d.sum(axis=0)
print("\n sum of row:", row_sum)
print("\n sum of column:", col_sum)

greater_than_10 = arr[arr > 10]
print("\n greater number than 10:", greater_than_10)

arr_replaced = np.where(arr%2 == 0, -1, arr)
print("/n array witn even number replaced:\n", arr_replaced.reshape(4, 5))

4*5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 sum of row: [15 40 65 90]

 sum of column: [34 38 42 46 50]

 greater number than 10: [11 12 13 14 15 16 17 18 19 20]
/n array witn even number replaced:
 [[ 1 -1  3 -1  5]
 [-1  7 -1  9 -1]
 [11 -1 13 -1 15]
 [-1 17 -1 19 -1]]


In [12]:
"""
5. Create two NumPy arrays A and B as shown below and perform:
A = np.array([[1, 2], [3, 4]]) B = np.array([[5, 6], [7, 8]])
a) Element-wise addition, subtraction, and multiplication.
b) Matrix multiplication using np.dot() or the @ operator.
c) Transpose of A.
d) The determinant and inverse of A using np.linalg
""";

In [33]:
A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])

addition =A+B
subtraction=A-B
multiplication=A*B

dot_result = np.dot(A, B)

transpose_A = A.T

det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)

print("\n", addition)
print("\n", subtraction)
print("\n", multiplication)
print("\n", dot_result)
print("\n", transpose_A)
print("\n", det_A)
print("\n", inv_A)


 [[ 6  8]
 [10 12]]

 [[-4 -4]
 [-4 -4]]

 [[ 5 12]
 [21 32]]

 [[19 22]
 [43 50]]

 [[1 3]
 [2 4]]

 -2.0000000000000004

 [[-2.   1. ]
 [ 1.5 -0.5]]


In [34]:
"""
6. Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint()
(set a seed of 42 for reproducibility). Then:
a) Find the mean, median, standard deviation, min, and max.
b) Sort the array in descending order.
c) Find the indices of the 3 largest values using np.argsort().
d) Normalize the array so all values lie between 0 and 1
""";

In [40]:
import numpy as np

np.random.seed(42)
arr = np.random.randint(1,101, size=15)

mean = np.mean(arr)
median = np.median(arr)
standard_deviation = np.std(arr)
min_v = np.min(arr)
max_v = np.max(arr)

sorted_desc = np.sort(arr)

indices_top3 = np.argsort(arr)[-3:][::-1]
Normalize = (arr - min_v) / (max_v - min_v)

print("\n Array", arr)
print("\n median", median)
print("\n mean", mean)
print("\n standard_deviation", standard_deviation)
print("\n min_v", min_v)
print("\n max_v", max_v)
print("\n sorted_desc", sorted_desc)
print("\n indices_top3", indices_top3)
print("\n Normalize", Normalize)


 Array [ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]

 median 72.0

 mean 58.06666666666667

 standard_deviation 31.4843170836247

 min_v 3

 max_v 100

 sorted_desc [  3  15  21  22  24  52  61  72  75  75  83  87  88  93 100]

 indices_top3 [11  1 10]

 Normalize [0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


# Section C — Pandas Basics

In [41]:
"""
7. Create a Pandas DataFrame from the dictionary below and perform the following:
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], "Age": [23, 21,
25, 22, 24], "Department": ["AI", "Data Science", "AI", "Web Dev", "Data
Science"], "Score": [88, 92, 79, 95, 67], }
a) Display the first 3 rows and the data types of each column.
b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').
c) Sort the DataFrame by Score in descending order
""";

In [47]:

import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67],
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

print("\nFirst 3 rows:\n", df.head(3))
print("\nData types:\n", df.dtypes)

df["Grade"] = df["Score"].apply(lambda s: "A" if s >= 90 else ("B" if s >= 75 else "C"))
print("\nDataFrame with Grade column:\n", df)

df_sorted = df.sort_values(by="Score", ascending=False)
print("\nDataFrame sorted by Score (descending):\n", df_sorted)

df_ai = df[df["Department"] == "AI"]
print("\nRows where Department is 'AI':\n", df_ai)

Original DataFrame:
     Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

First 3 rows:
     Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

Data types:
 Name          object
Age            int64
Department    object
Score          int64
dtype: object

DataFrame with Grade column:
     Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

DataFrame sorted by Score (descending):
     Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25     

In [48]:
"""
8. Using the same DataFrame from Q7:
a) Group by Department and find the average Score for each.
b) Find the row with the highest Score using idxmax().
c) Rename the column Score to Marks.
d) Drop the Age column and display the resulting DataFrame.
""";

In [51]:
import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67],
}

df = pd.DataFrame(data)

avg_scores = df.groupby("Department")["Score"].mean()
print("Average Score by Department:\n", avg_scores)

highest_row = df.loc[df["Score"].idxmax()]
print("\nRow with highest Score:\n", highest_row)

df.rename(columns={"Score": "Marks"}, inplace=True)
print("\nDataFrame with 'Score' renamed to 'Marks':\n", df)

df_dropped = df.drop(columns=["Age"])
print("\nDataFrame after dropping 'Age':\n", df_dropped)


Average Score by Department:
 Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64

Row with highest Score:
 Name            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object

DataFrame with 'Score' renamed to 'Marks':
     Name  Age    Department  Marks
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

DataFrame after dropping 'Age':
     Name    Department  Marks
0  Aarav            AI     88
1  Priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil  Data Science     67


In [52]:
"""
9. Create a DataFrame with some missing values as shown below and handle them:
import numpy as np data = { "Product": ["Pen", "Notebook", "Eraser",
"Sharpener", "Ruler"], "Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50,
np.nan, 30, 20], }
a) Check the number of missing values in each column using isnull().sum().
b) Fill missing Price values with the column mean.
c) Drop rows where Stock is still missing.
""";

In [58]:
import pandas as pd
import numpy as np

data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20],
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

print("\nMissing values per column:\n", df.isnull().sum())

mean_price = df["Price"].mean()
df["Price"].fillna(mean_price, inplace=True)
print("\nDataFrame after filling missing Price with mean:\n", df)

df_cleaned = df.dropna(subset=["Stock"])
print("\nDataFrame after dropping rows with missing Stock:\n", df_cleaned)

df_cleaned.to_csv("cleaned_products.csv", index=False)
print("\n✅ Cleaned DataFrame saved to 'cleaned_products.csv'")


Original DataFrame:
      Product  Price  Stock
0        Pen   10.0  100.0
1   Notebook    NaN   50.0
2     Eraser    5.0    NaN
3  Sharpener    8.0   30.0
4      Ruler    NaN   20.0

Missing values per column:
 Product    0
Price      2
Stock      1
dtype: int64

DataFrame after filling missing Price with mean:
      Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2     Eraser   5.000000    NaN
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

DataFrame after dropping rows with missing Stock:
      Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

✅ Cleaned DataFrame saved to 'cleaned_products.csv'


C:\Users\Samruddhi Deshmukh\AppData\Local\Temp\ipykernel_6348\2855417548.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(mean_price, inplace=True)


In [59]:
"""
10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:
a) Print its shape and column names.
b) Add a new column Total_Value as Price multiplied by Stock.
c) Use describe() to print summary statistics of the numeric columns.
d) Wrap the file reading step in a try-except block to handle the case where the file does not
exist (FileNotFoundError)
""";

In [60]:
import pandas as pd

try:
    df = pd.read_csv("cleaned_products.csv")
    print("✅ File loaded successfully!")

    print("\nShape of DataFrame:", df.shape)
    print("Column names:", df.columns.tolist())

    df["Total_Value"] = df["Price"] * df["Stock"]
    print("\nDataFrame with Total_Value column:\n", df)

    print("\nSummary statistics:\n", df.describe())

except FileNotFoundError:
    print("❌ Error: 'cleaned_products.csv' not found. Please make sure the file exists.")


✅ File loaded successfully!

Shape of DataFrame: (4, 3)
Column names: ['Product', 'Price', 'Stock']

DataFrame with Total_Value column:
      Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

Summary statistics:
            Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
