In [1]:
# numPy

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
#creating arrays

In [5]:
sample_array = np.array([1,2,3,4])  

In [6]:
sample_array

array([1, 2, 3, 4])

In [9]:
sample_array2= np.array([1,2,3,44,4,5,67,79])

In [10]:
sample_array2

array([ 1,  2,  3, 44,  4,  5, 67, 79])

In [11]:
# 2D array(a matrix) with 2 rows and 2 columns

In [14]:
sample_array1 = np.array([[1,2],[3,4]])

In [15]:
sample_array1

array([[1, 2],
       [3, 4]])

In [16]:
sam = np.array([[23,42,44],[12,34,45]])

In [17]:
sam

array([[23, 42, 44],
       [12, 34, 45]])

In [18]:
# 3D tensor (2 marsices, each with 2 rows and 2 columns)

In [21]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [22]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
sample_tensor_4 = np.array([[[1,2,2,3,4],[3,4,3,7,9]],[[5,6,4,6,5],[7,8,2,6,7]]])

In [25]:
sample_tensor_4

array([[[1, 2, 2, 3, 4],
        [3, 4, 3, 7, 9]],

       [[5, 6, 4, 6, 5],
        [7, 8, 2, 6, 7]]])

In [26]:
# dimension

In [30]:
# 0-D Array(scalar) 5
# 1-D Array(vector) [1,2,3,4]
# 2-D Array(matrix) (rows,columns)
# 3-D array(tensor) (page, rows, column)

In [32]:
# Array Properties

In [33]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [34]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# shape

In [36]:
sample_array.shape

(2, 3)

In [37]:
# dimensions

In [38]:
sample_array.ndim

2

In [39]:
#total elements


In [40]:
sample_array.size

6

In [41]:
# data type

In [42]:
sample_array.dtype

dtype('int64')

In [43]:
arr = np.array([
            [
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
            ],
            [
                [13, 14, 15, 16],
                [17, 18, 19, 20],
                [21, 22, 23, 24]
            ]
        ])

In [44]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [45]:
#Shape
arr.shape

(2, 3, 4)

In [47]:
# dimensions
arr.ndim

3

In [48]:
#total elements
arr.size

24

In [49]:
# special array

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [53]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [57]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [60]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [61]:
# indexing & Slicing

In [62]:
sample_array = np.array([10,20,30,40])

In [63]:
sample_array

array([10, 20, 30, 40])

In [64]:
sample_array[2]

np.int64(30)

In [65]:
sample_array[0]

np.int64(10)

In [66]:
sample_array[-1]

np.int64(40)

In [67]:
sample_array[-4]

np.int64(10)

In [68]:
 # Slicing

In [70]:
sample_array[1:3]

array([20, 30])

In [74]:
sample_array[0:4]

array([10, 20, 30, 40])

In [75]:
# array operation

In [77]:
a = np.array([4,5,6])

In [82]:
b = np.array([1,2,3])

In [83]:
a

array([4, 5, 6])

b


In [84]:
a + b

array([5, 7, 9])

In [85]:
a*b

array([ 4, 10, 18])

In [86]:
a/b

array([4. , 2.5, 2. ])

In [90]:
a = np.array([2,3,4])

In [91]:
b = np.array([12,23,34])

In [92]:
a+b

array([14, 26, 38])

In [93]:
a-b

array([-10, -20, -30])

In [94]:
a*b

array([ 24,  69, 136])

In [95]:
a/b

array([0.16666667, 0.13043478, 0.11764706])

In [96]:
# mathematical function

In [105]:
sample_array = np.array([1,4,9])

sample_array

In [106]:
sample_array

array([1, 4, 9])

In [107]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [108]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [112]:
a = np.array([4,5,6])

In [114]:
np.exp(a)

array([ 54.59815003, 148.4131591 , 403.42879349])

In [116]:
np.log(a)

array([1.38629436, 1.60943791, 1.79175947])

In [117]:
arr = np.array([23,45,67])

In [118]:
arr

array([23, 45, 67])

In [119]:
np.log(arr)

array([3.13549422, 3.80666249, 4.20469262])

In [120]:
#statistical functions

In [121]:
sample_array

array([1, 4, 9])

In [122]:
np.min(sample_array)

np.int64(1)

In [124]:
np.median(sample_array)

np.float64(4.0)

In [125]:
np.std(sample_array)

np.float64(3.2998316455372216)

In [126]:
np.min(sample_array)

np.int64(1)

In [127]:
np.max(sample_array)

np.int64(9)

In [128]:
# reshaping arrays

In [139]:
arr=np.arange(5)

In [140]:
arr

array([0, 1, 2, 3, 4])

In [141]:
reshaped = arr.reshape(2,3)

ValueError: cannot reshape array of size 5 into shape (2,3)

In [142]:
# flattening

In [145]:
arr = np.array([[1,3],[4,5]])

In [146]:
arr

array([[1, 3],
       [4, 5]])

In [147]:
arr.flatten()

array([1, 3, 4, 5])

In [149]:
arr=np.array([[4,6,7,9],[2,4,6,9],[2,6,8,4]])


In [150]:
arr

array([[4, 6, 7, 9],
       [2, 4, 6, 9],
       [2, 6, 8, 4]])

In [151]:
arr.flatten()

array([4, 6, 7, 9, 2, 4, 6, 9, 2, 6, 8, 4])

In [152]:
# joining arrays 

In [154]:
a=np.array([1,2])

In [155]:
b=np.array([3,4])

In [156]:
a

array([1, 2])

In [157]:
b

array([3, 4])

In [158]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [159]:
np.concat((a,b))

array([1, 2, 3, 4])

In [160]:
# splitting arrays

In [161]:
arr = np.array([1,2,3,4])

In [162]:
arr

array([1, 2, 3, 4])

In [166]:
np.array_split(arr,2)

[array([1, 2]), array([3, 4])]

In [167]:
# random modeul

In [168]:
np.random.rand(3)

array([0.65186699, 0.79120593, 0.23634879])

In [169]:
np.random.randint(1,10,5)

array([2, 9, 2, 8, 9], dtype=int32)

In [170]:
# Axis concept

In [171]:
arr =np.array([[1,2],[3,4]])

In [172]:
arr

array([[1, 2],
       [3, 4]])

In [173]:
np.sum(arr,axis=0)

array([4, 6])

In [174]:
np.sum(arr,axis=1)

array([3, 7])

In [175]:
# nan & missing values

In [176]:
sample_array =np.array([1,np.nan,3])

In [177]:
sample_array

array([ 1., nan,  3.])

In [178]:
np.isnan(sample_array)

array([False,  True, False])

In [179]:
# create 2 numpy arrays and perform element wise addition subtraction multiplication ,and modules operation


In [180]:
arr1 = np.array([1,2,3,4])

In [181]:
arr2=np.array([5,6,7,8])

In [182]:
arr1

array([1, 2, 3, 4])

In [183]:
arr2

array([5, 6, 7, 8])

In [188]:
arr1 + arr2

array([ 6,  8, 10, 12])

In [189]:
arr1 - arr2


array([-4, -4, -4, -4])

In [190]:
arr1 * arr2


array([ 5, 12, 21, 32])

In [191]:
arr1 / arr2


array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [192]:
# pandas

In [194]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [195]:
# 1D data structures in pandas

In [196]:
# pandas series

In [197]:
#creating pandas series


In [202]:
import pandas as pd

In [204]:
s = pd.Series([10,20,30])

In [205]:
s

0    10
1    20
2    30
dtype: int64

In [206]:
a = pd.Series([23,45,67,51])

In [207]:
a

0    23
1    45
2    67
3    51
dtype: int64

In [209]:
s = pd.Series([10,20,30], index =['a','b','c'])

In [210]:
s

a    10
b    20
c    30
dtype: int64

In [213]:
# with costom index

In [214]:
s = pd.Series(['samruddhi',19,90], index =['name','age','marks'])

In [215]:
s

name     samruddhi
age             19
marks           90
dtype: object

In [216]:
# from dictionary

In [217]:
data = {'name':"samruddhi",'age':19,'marks':90}

In [218]:
data

{'name': 'samruddhi', 'age': 19, 'marks': 90}

In [219]:
s = pd.Series(data)

In [220]:
s


name     samruddhi
age             19
marks           90
dtype: object

In [221]:
# from a single value

In [222]:
s = pd.Series(5,index=[0,1,2,3])

In [223]:
s

0    5
1    5
2    5
3    5
dtype: int64

In [224]:
# attributes

In [225]:
s = pd.Series([10,20,30],index=['a,','b','c'])

In [226]:
s

a,    10
b     20
c     30
dtype: int64

In [227]:
s.values

array([10, 20, 30])

In [228]:
s.index

Index(['a,', 'b', 'c'], dtype='object')

In [229]:
s.dtype

dtype('int64')

In [230]:
s.shape

(3,)

In [231]:
# data manipulation

In [232]:
s = pd.Series([1,2,3])

In [233]:
print(s*3)

0    3
1    6
2    9
dtype: int64


In [234]:
# handling missing values

In [237]:
s = pd.Series([1,None,3])

In [238]:
s

0    1.0
1    NaN
2    3.0
dtype: float64

In [240]:
s.isnull()

0    False
1     True
2    False
dtype: bool

In [241]:
s.dropna()

0    1.0
2    3.0
dtype: float64

In [243]:
s.fillna(0)

0    1.0
1    0.0
2    3.0
dtype: float64

In [244]:
# indexing

In [245]:
s = pd.Series([10,20,30], index=['a','b','c'])

In [246]:
s

a    10
b    20
c    30
dtype: int64

In [247]:
s['a']

np.int64(10)

In [248]:
s['b']

np.int64(20)